---
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - mysql

# clone repo
- name: Clone tooling repo
  ansible.builtin.git:
    repo: https://github.com/MekkyMayata/tooling.git
    dest: /home/ec2-user/tooling
  
- name: move code to /var/www/html directory
  command: cp -r /home/ec2-user/tooling/{{ item }} /var/www/html/
  with_items:
    - "html/."

- name: edit db connection
  shell: sed -i "s/'mysql.tooling.svc.cluster.local', 'admin', 'admin', 'tooling'/'172.31.0.14', 'webaccess', 'password', 'tooling'/" /var/www/html/functions.php
