---
- name: install packages and repositories
  package:
    name: "{{ item }}"
    state: present
  loop:
    # - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    # - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    - git
    - mysql
    - php
    - php-cli
    - php-common
    - php-gd
    - php-mysqlnd

# - name: Enable DNF module
#   shell: dnf module enable -y php:remi-8.0

# - name: start and enable services
#   service:
#     name: php-fpm
#     state: started
#     enabled: yes
  # notify:
  #   - restart apache


# clone repo
- name: Clone tooling repo
  ansible.builtin.git:
    repo: https://github.com/MekkyMayata/tooling.git
    dest: /home/ec2-user/tooling
  
- name: move code to /var/www/html directory
  command: cp -r /home/ec2-user/tooling/{{ item }} /var/www/html/
  with_items:
    - "html/."

- name: edit db connection
  shell: sed -i "s/'mysql.tooling.svc.cluster.local', 'admin', 'admin', 'tooling'/'172.31.0.14', 'webaccess', 'password', 'tooling'/" /var/www/html/functions.php
