---
- name: Add repository
  yum_repository:
    name: "{{ item.name }}"
    description: EPEL YUM repo
    baseurl: "{{ item.baseurl }}"
    enabled: yes
  loop:
    - { name: 'epel', baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm }
    - { name: 'php:remi-8.0', baseurl: https://rpms.remirepo.net/enterprise/remi-release-8.rpm }

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - mysql
    - php
    - php-cli
    - php-common
    - php-gd
    - php-mysqlnd

- name: start and enable services
  service:
    name: php-fpm
    state: started
    enabled: yes
  notify:
    - restart apache


# clone repo
- name: Clone tooling repo
  ansible.builtin.git:
    repo: https://github.com/MekkyMayata/tooling.git
    dest: /home/ec2-user/tooling
  
- name: move code to /var/www/html directory
  command: cp -r /home/ec2-user/tooling/{{ item }} /var/www/html/
  with_items:
    - "html/."

- name: edit db connection
  shell: sed -i "s/'mysql.tooling.svc.cluster.local', 'admin', 'admin', 'tooling'/'172.31.0.14', 'webaccess', 'password', 'tooling'/" /var/www/html/functions.php
