---
# handlers file for sonarqube
- name: reload system settings
  shell: sysctl --system

- name: java version
  shell: java -version

- name: apt update and upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 0

#******NB: ansible-galaxy collection install ansible.posix
- name: Mount swap
  ansible.posix.mount:
    path: none
    src: /swapfile
    fstype: swap
    state: present