---
- name: Include dynamic variables
  hosts: all

- name: import the common playbook
  import_playbook: ../static-assignments/common.yml
  tags:
    - skip

- name: include the env-vars playbook
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - skip

- name: include playbook for db server
  import_playbook: ../static-assignments/db.yml
  tags:
    - run

- name: Include playbook for tooling webserver
  import_playbook: ../static-assignments/webservers.yml
  tags:
    - run

- name: include playbook for artifact_repository
  import_playbook: ../static-assignments/artifactory.yml
  tags:
    - run

- name: import sonarqube playbook
  import_playbook: ../static-assignments/sonarqube.yml
  tags:
    - run

# - name: include playbook for webserver-todo-php
#   import_playbook: ../static-assignments/webserver-todo-php.yml

- name: include playbook for nginx reverse proxy
  import_playbook: ../static-assignments/nginx.yml